In [2]:
import time
import re
import requests 
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (9, 5)

BASE_URL = "https://books.toscrape.com/"
CATALOGUE_URL = BASE_URL + "catalogue/"
HEADERS = {"User-Agent": "Mozilla/5.0 (Scraper)"}

RATING_WORDS = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

## 1: Data Acquisition

In [4]:
def get_group(url):
    """Fetch a URL and return a BeautifulSoup obect."""
    response = requests.get(url, headers=HEADERS)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def get_category_links():
    """Return a dict of {genre_name: category_index_url} for all genres on the site."""
    soup = get_group(BASE_URL)
    nav_links = soup.select("div.side_categories ul li ul li a")
    categories = {}
    for a in nav_links:
        genre = a.get_text(strip=True)
        href = a["href"]
        categories[genre] = BASE_URL + href
    return categories


def parse_book_card(card, genre):
    """Extract raw fields from a single book card, including raw stock text from its detail page."""
    title = card.h3.a["title"]
    price_raw = card.select_one(".price_color").text.strip()      
    rating_word = card.select_one(".star-rating")["class"][1]     

    relative_href = card.h3.a["href"]
    detail_url = CATALOGUE_URL + relative_href.replace("../../../", "")
    detail_soup = get_group(detail_url)
    availability_raw = detail_soup.select_one(".instock.availability").text.strip()  
    time.sleep(0.2)

    return {
        "title": title,
        "price_raw": price_raw,
        "rating_word": rating_word,
        "availability_raw": availability_raw,
        "genre": genre,
    }

def scrape_category(genre, start_url):
    """Walk every paginated listing page of one category and return a list of book dicts."""
    records = []
    url = start_url
    while url:
        soup = get_group(url)
        cards = soup.select("article.product_pod")
        for card in cards:
            records.append(parse_book_card(card, genre))

        next_link = soup.select_one("li.next a")
        if next_link:
            url = url.rsplit("/", 1)[0] + "/" + next_link["href"]
        else:
            url = None
        time.sleep(0.3)
    return records


def scrape_full_catalogue():
    """Scrape every genre in full and return all books as raw records."""
    categories = get_category_links()
    all_records = []
    print(f"Found {len(categories)} genres. Scraping...")

    for genre, url in categories.items():
        recs = scrape_category(genre, url)
        print(f"  {genre:<25s} {len(recs):>4d} books")
        all_records.extend(recs)

    return pd.DataFrame(all_records)

df = scrape_full_catalogue()
print(f"Collected {len(df)} books.")
print(df.head())

df.to_csv("books_raw.csv", index=False)

Found 50 genres. Scraping...
  Travel                      11 books
  Mystery                     32 books
  Historical Fiction          26 books
  Sequential Art              75 books
  Classics                    19 books
  Philosophy                  11 books
  Romance                     35 books
  Womens Fiction              17 books
  Fiction                     65 books
  Childrens                   29 books
  Religion                     7 books
  Nonfiction                 110 books
  Music                       13 books
  Default                    152 books
  Science Fiction             16 books
  Sports and Games             5 books
  Add a comment               67 books
  Fantasy                     48 books
  New Adult                    6 books
  Young Adult                 54 books
  Science                     14 books
  Poetry                      19 books
  Paranormal                   1 books
  Art                          8 books
  Psychology                   7 books
  Autobiography                9 books
  Parenting                    1 books
  Adult Fiction                1 books
  Humor                       10 books
  Horror                      17 books
  History                     18 books
  Food and Drink              30 books
  Christian Fiction            6 books
  Business                    12 books
  Biography                    5 books
  Thriller                    11 books
  Contemporary                 3 books
  Spirituality                 6 books
  Academic                     1 books
  Self Help                    5 books
  Historical                   2 books
  Christian                    3 books
  Suspense                     1 books
  Short Stories                1 books
  Novels                       1 books
  Health                       4 books
  Politics                     3 books
  Cultural                     1 books
  Erotica                      1 books
  Crime                        1 books
Collected 1000 books.
                                               title price_raw rating_word  \
0                            It's Only the Himalayas   Â£45.17         Two
1  Full Moon over Noahâs Ark: An Odyssey to Mou...   Â£49.43        Four
2  See America: A Celebration of Our National Par...   Â£48.87       Three
3  Vagabonding: An Uncommon Guide to the Art of L...   Â£36.94         Two
4                               Under the Tuscan Sun   Â£37.33       Three

          availability_raw   genre
0  In stock (19 available)  Travel
1  In stock (15 available)  Travel
2  In stock (14 available)  Travel
3   In stock (8 available)  Travel
4   In stock (7 available)  Travel

In [3]:
df = pd.read_csv("books_raw.csv")
print("Shape:", df.shape)
print("\nColumn types:")
print(df.dtypes)
print("\nMissing values per column:")
print(df.isnull().sum())
print("\nFirst 5 rows:")
df.head()

Shape: (1000, 5)

Column types:
title               object
price_raw           object
rating_word         object
availability_raw    object
genre               object
dtype: object

Missing values per column:
title               0
price_raw           0
rating_word         0
availability_raw    0
genre               0
dtype: int64

First 5 rows:

,title,price_raw,rating_word,availability_raw,genre
0,It's Only the Himalayas,Â£45.17,Two,In stock (19 available),Travel
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Â£49.43,Four,In stock (15 available),Travel
2,See America: A Celebration of Our National Par...,Â£48.87,Three,In stock (14 available),Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,Â£36.94,Two,In stock (8 available),Travel
4,Under the Tuscan Sun,Â£37.33,Three,In stock (7 available),Travel

In [4]:
def fix(text):
    """Repair text that was UTF-8 but got mis-coded as Latin-1"""
    if not isinstance(text, str):
        return text
    try:
        return text.encode("latin1").decode("utf-8")
    except (UnicodeDecodeError, UnicodeEncodeError):
        return text

df["title"]= df["title"].apply(fix)
df["price_raw"] = df["price_raw"].apply(fix)

df[["title", "price_raw"]].head()

                                               title price_raw
0                            It's Only the Himalayas    £45.17
1  Full Moon over Noah’s Ark: An Odyssey to Mount...    £49.43
2  See America: A Celebration of Our National Par...    £48.87
3  Vagabonding: An Uncommon Guide to the Art of L...    £36.94
4                               Under the Tuscan Sun    £37.33

In [7]:
df["price"] = (
    df["price_raw"]
    .str.replace("£", "", regex=False)
    .str.strip()
    .astype(float)
)

print(df[["price_raw", "price"]].head())
print("\nAny missing prices?", df["price"].isnull().sum())

  price_raw  price
0    £45.17  45.17
1    £49.43  49.43
2    £48.87  48.87
3    £36.94  36.94
4    £37.33  37.33

Any missing prices? 0